sonar.projectKey=front-heuristicas
sonar.projectName=front-heuristicas
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.token=sqp_765100325fe8491cd5e9623a31b8f0a118039a11
sonar.projectBaseDir=.

sonar.sources=src
sonar.tests=src,tests

sonar.test.inclusions=\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx

sonar.inclusions=\
  src/app/dashboard/page.tsx,\
  src/app/account/permissions/page.tsx,\
  src/app/account/roles/page.tsx,\
  src/app/account/users/page.tsx,\
  src/app/**/login/page.tsx,\
  src/app/**/register/page.tsx,\
  src/app/project/**/assignments/page.tsx,\
  src/components/layout/sidebar.tsx,\
  src/features/auth/services/auth.service.ts,\
  src/features/evaluations/hooks/useEvaluation.ts

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/.next/**,\
  **/assets/**

sonar.coverage.exclusions=\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  src/lighthouse/**,\
  src/features/projects/services/**,\
  src/features/evaluations/services/**,\
  src/components/ui/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
