sonar.projectKey=front-heuristicas
sonar.projectName=front-heuristicas
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.token=sqp_efc5949712a11b351aa3861f4dc02625058f9216
sonar.sources=src
sonar.tests= src
sonar.test.inclusions=\
  src/app/(auth)/login/page.test.tsx,\
  src/app/(auth)/register/page.test.tsx,\
  src/app/account/roles/page.test.tsx,\
  src/features/auth/services/auth.service.test.ts

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/.next/**,\
  **/assets/**

sonar.coverage.exclusions=src/components/**, src/app/(auth)/login/page.test.tsx, src/app/(auth)/register/page.test.tsx, src/app/account/roles/page.test.tsx, src/features/auth/services/auth.service.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.projectBaseDir=.