services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - jenkins_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - jenkins_network

networks:
  jenkins_network:
    external: true
    name: bridge