sonar.projectKey=back-heuristicas
sonar.projectName=back-heuristicas
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.token=sqp_f503897303e4721cd3d7a59a22a5d6494f29bb77

sonar.sources=src,analytics
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py


sonar.exclusions=\
  **/__pycache__/**,\
  **/venv/**,\
  **/.pytest_cache/**,\
  check_db.py,\
  main.py

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
sonar.projectBaseDir=.

sonar.python.version=3.11
